=== NguyenTruong150197/FPT-Sem2/T2207E/Markup Language and JSON/Bai3/Ví dụ demo/vidu3/studentSchema2.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[a-zA-Z]{3}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="id" type="xs:integer"/>
                <xs:element name="gender">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="male|female"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="contactInfo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="address" type="addressType" />
                            <xs:element name="phone" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="addressType">
        <xs:sequence>
            <xs:element name="province" type="xs:string"/>
            <xs:element name="district" type="xs:string"/>
            <xs:element name="commune" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== NguyenTruong150197/FPT-Sem2/T2207E/Markup_Language_and_JSON/Bai3/Ví dụ demo/vidu3/student2.xml
<?xml version="1.0" encoding="UTF-8"?>
<student
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='studentSchema2.xsd'>
    <name>abc</name>
    <id>111</id>
    <gender>male</gender>
    <contactInfo>
        <address>
            <province>Ha noi</province>
            <district>Cau giay</district>
            <commune>Dich vong</commune>
        </address>
        <phone>09123</phone>
    </contactInfo>
</student>
